name       : python-selenium
version    : 3.141.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/ed/9c/9030520bf6ff0b4c98988448a93c04fcbd5b13cd9520074d8ed53569ccfe/selenium-3.141.0.tar.gz : deaf32b60ad91a4611b98d8002757f29e6f2c2d5fcaf202e1c9ad06d6772300d
homepage   : http://www.seleniumhq.org
license    : Apache-2.0
component  : programming.python
summary    : A browser automation framework and ecosystem.
description: |
    Selenium is an umbrella project encapsulating a variety of tools and libraries enabling web browser automation. Selenium specifically provides infrastructure for the W3C WebDriver specification — a platform and language-neutral coding interface compatible with all major web browsers.
rundeps    :
    - geckodriver
    - python-urllib3
build      : |
    %python3_setup
install    : |
    %python3_install
